### ISSUE TITLE
Creates the 'book_path' variable at config instead the 'library' variable

### ISSUE THREAD

**Issue by crrlcx** [mak-alex/backlitr#1]
Creates the `book_path:` variable at config instead the `library` variable

Look a like wrong name used at [this](https://github.com/mak-alex/litres-backup/blob/9905acb58da8cc2a93a415c9d5c9144d816cdb7b/pkg/conf/conf.go#L26) line.

**Comment by mak-alex** [comment]
Hi, thanks for the comment, corrected)
